# Copyright (c) 2014-present, Facebook, Inc. All rights reserved.
#
# You are hereby granted a non-exclusive, worldwide, royalty-free license to use,
# copy, modify, and distribute this software in source code or binary form for use
# in connection with the web services and APIs provided by Facebook.
#
# As with any software that integrates with the Facebook platform, your use of
# this software is subject to the Facebook Developer Principles and Policies
# [http://developers.facebook.com/policy/]. This copyright notice shall be
# included in all copies or substantial portions of the software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
# FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
# COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
# IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

name: FBSDKLoginKit

include:
  - ../xcodegen_project_common.yml

projectReferences:
  FBSDKCoreKit_Basics:
    path: ../FBSDKCoreKit_Basics/FBSDKCoreKit_Basics.xcodeproj
  FBSDKCoreKit:
    path: ../FBSDKCoreKit/FBSDKCoreKit.xcodeproj
  TestTools:
    path: ../TestTools/TestTools.xcodeproj
  OCMock:
    path: ../Carthage/Checkouts/ocmock/Source/OCMock.xcodeproj

options:
  deploymentTarget:
    tvOS: "10.0"

configFiles:
  Debug: Configurations/Shared/Configuration/Debug.xcconfig
  Release: Configurations/Shared/Configuration/Release.xcconfig

settings:
  base:
    # Some iOS defaults will be overridden by Xcodegen.
    # We need to explicitly set them to maintain parity with
    # the project file being replaced
    CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER: NO
    SWIFT_OPTIMIZATION_LEVEL: -O
    ENABLE_NS_ASSERTIONS: YES
    PRODUCT_NAME: FBSDKLoginKit

targets:
  FBSDKLoginKit:
    type: framework
    platform: iOS
    sources:
      - path: ../FBSDKCoreKit/FBSDKCoreKit/Internal/FBSDKCoreKit+Internal.h
        headerVisibility: project
        group: FBSDKLoginKit/Internal
      - path: FBSDKLoginKit
        headerVisibility: public
        excludes:
          - Internal
          - include
          - Info.plist
          - Swift
      - path: FBSDKLoginKit/Internal
        headerVisibility: project
        createIntermediateGroups: true
      - path: FBSDKLoginKit/Swift
        excludes:
          - Exports.swift
        createIntermediateGroups: true
    configFiles:
      Debug: Configurations/FBSDKLoginKit.xcconfig
      Release: Configurations/FBSDKLoginKit.xcconfig
    dependencies:
      - target: FBSDKCoreKit_Basics/FBSDKCoreKit_Basics
        link: false
      - target: FBSDKCoreKit/FBSDKCoreKit
        link: false
    preBuildScripts:
      - name: Run Swiftlint
        script: |
          # Type a script or drag a script file from your workspace to insert its path.
          if which swiftlint >/dev/null; then
            swiftlint --config ../.swiftlint.yml
          else
            echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
          fi
    settings:
      CLANG_WARN_STRICT_PROTOTYPES: NO
  FBSDKLoginKit-Dynamic:
    type: framework
    platform: iOS
    productName: FBSDKLoginKit
    sources:
      - path: ../FBSDKCoreKit/FBSDKCoreKit/Internal/FBSDKCoreKit+Internal.h
        headerVisibility: project
        group: FBSDKLoginKit/Internal
      - path: FBSDKLoginKit
        headerVisibility: public
        excludes:
          - Internal
          - include
          - Info.plist
          - Swift
      - path: FBSDKLoginKit/Internal
        headerVisibility: project
        createIntermediateGroups: true
      - path: FBSDKLoginKit/Swift
        excludes:
          - Exports.swift
        createIntermediateGroups: true
    configFiles:
      Debug: Configurations/FBSDKLoginKit-Dynamic.xcconfig
      Release: Configurations/FBSDKLoginKit-Dynamic.xcconfig
    dependencies:
      - target: FBSDKCoreKit_Basics/FBSDKCoreKit_Basics-Dynamic
      - target: FBSDKCoreKit/FBSDKCoreKit-Dynamic
      - sdk: UIKit.framework
      - sdk: CoreGraphics.framework
    preBuildScripts:
      - name: Run Swiftlint
        script: |
          # Type a script or drag a script file from your workspace to insert its path.
          if which swiftlint >/dev/null; then
            swiftlint --config ../.swiftlint.yml
          else
            echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
          fi
    settings:
      CLANG_WARN_STRICT_PROTOTYPES: NO
      PRODUCT_NAME: FBSDKLoginKit
  FBSDKLoginKit_TV:
    type: framework
    platform: tvOS
    productName: FBSDKLoginKit
    sources:
      - path: ../FBSDKCoreKit/FBSDKCoreKit/Internal/FBSDKCoreKit+Internal.h
        headerVisibility: project
        group: FBSDKLoginKit/Internal
      - path: FBSDKLoginKit
        headerVisibility: public
        excludes:
          - FBSDKLoginConfiguration.[h,m]
          - FBSDKReferral*
          - FBSDKLoginButton*
          - FBSDKLoginConfiguration
          - FBSDKLoginManager.[h,m]
          - FBSDKLoginManagerLoginResult*
          - FBSDKLoginTooltipView*
          - FBSDKTooltipView*
          - Internal
          - include
          - Info.plist
          - Swift/*.swift
      - path: FBSDKLoginKit/Internal
        headerVisibility: project
        excludes:
          - FBSDKAuthenticationToken*
          - _FBSDKLoginRecoveryAttempter*
          - FBSDKLoginCompletion*
          - FBSDKLoginError*
          - FBSDKLoginManagerLogger*
          - FBSDKLoginUtility*
          - FBSDKMonotonicTime*
          - FBSDKPermission*
          - FBSDKProfileFactory*
          - FBSDKReferral*
          - FBSDKProfileCreating*
        createIntermediateGroups: true
    configFiles:
      Debug: Configurations/FBSDKLoginKit-tvOS.xcconfig
      Release: Configurations/FBSDKLoginKit-tvOS.xcconfig
    dependencies:
      - target: FBSDKCoreKit_Basics/FBSDKCoreKit_Basics_TV
        link: false
      - target: FBSDKCoreKit/FBSDKCoreKit_TV
        link: false
    preBuildScripts:
      - name: Run Swiftlint
        script: |
          # Type a script or drag a script file from your workspace to insert its path.
          if which swiftlint >/dev/null; then
            swiftlint --config ../.swiftlint.yml
          else
            echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
          fi
    settings:
      CLANG_WARN_STRICT_PROTOTYPES: NO
      PRODUCT_NAME: FBSDKLoginKit
  FBSDKLoginKit_TV-Dynamic:
    type: framework
    platform: tvOS
    productName: FBSDKLoginKit
    sources:
      - path: ../FBSDKCoreKit/FBSDKCoreKit/Internal/FBSDKCoreKit+Internal.h
        headerVisibility: project
        group: FBSDKLoginKit/Internal
      - path: FBSDKLoginKit
        headerVisibility: public
        excludes:
          - FBSDKLoginConfiguration.[h,m]
          - FBSDKReferral*
          - FBSDKLoginButton*
          - FBSDKLoginConfiguration
          - FBSDKLoginManager.[h,m]
          - FBSDKLoginManagerLoginResult*
          - FBSDKLoginTooltipView*
          - FBSDKTooltipView*
          - Internal
          - include
          - Info.plist
          - Swift/*.swift
      - path: FBSDKLoginKit/Internal
        headerVisibility: project
        excludes:
          - FBSDKAuthenticationToken*
          - _FBSDKLoginRecoveryAttempter*
          - FBSDKLoginCompletion*
          - FBSDKLoginError*
          - FBSDKLoginManagerLogger*
          - FBSDKLoginUtility*
          - FBSDKMonotonicTime*
          - FBSDKPermission*
          - FBSDKProfileFactory*
          - FBSDKReferral*
          - FBSDKProfileCreating*
        createIntermediateGroups: true
    configFiles:
      Debug: Configurations/FBSDKLoginKit-tvOS-Dynamic.xcconfig
      Release: Configurations/FBSDKLoginKit-tvOS-Dynamic.xcconfig
    dependencies:
      - target: FBSDKCoreKit_Basics/FBSDKCoreKit_Basics_TV-Dynamic
      - target: FBSDKCoreKit/FBSDKCoreKit_TV-Dynamic
      - sdk: UIKit.framework
      - sdk: CoreGraphics.framework
    preBuildScripts:
      - name: Run Swiftlint
        script: |
          # Type a script or drag a script file from your workspace to insert its path.
          if which swiftlint >/dev/null; then
            swiftlint --config ../.swiftlint.yml
          else
            echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
          fi
    settings:
      CLANG_WARN_STRICT_PROTOTYPES: NO
      PRODUCT_NAME: FBSDKLoginKit
  FBSDKLoginKitTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - FBSDKLoginKitTests
    configFiles:
      Debug: Configurations/FBSDKLoginKitTests.xcconfig
      Release: Configurations/FBSDKLoginKitTests.xcconfig
    dependencies:
      - target: FBSDKLoginKit-Dynamic
        embed: false
      - target: TestTools/TestTools
        embed: false
      - target: OCMock/OCMock iOS
        embed: false
    settings:
      GCC_WARN_UNUSED_FUNCTION: NO

aggregateTargets:
  FBSDKLoginKit-Universal:
    targets: [FBSDKLoginKit]
    configFiles:
      Debug: Configurations/FBSDKLoginKit.xcconfig
      Release: Configurations/FBSDKLoginKit.xcconfig
    buildScripts:
      - name: ShellScript
        path: ../scripts/xcode/build-universal-framework.sh
  FBSDKLoginKit_TV-Universal:
    targets: [FBSDKLoginKit_TV]
    configFiles:
      Debug: Configurations/FBSDKLoginKit-tvOS.xcconfig
      Release: Configurations/FBSDKLoginKit-tvOS.xcconfig
    buildScripts:
      - name: ShellScript
        path: ../scripts/xcode/build-universal-tvos-framework.sh

schemes:
  FBSDKLoginKit:
    build:
      targets:
        FBSDKLoginKit: all
  FBSDKLoginKit-Dynamic:
    build:
      targets:
        FBSDKLoginKit-Dynamic: all
    test:
      targets:
        - FBSDKLoginKitTests
        - FBSDKCoreKit/FBSDKCoreKitTests
      coverageTargets:
        - FBSDKLoginKit
        - FBSDKCoreKit/FBSDKCoreKit
  FBSDKLoginKit_TV-Dynamic:
    build:
      targets:
        FBSDKLoginKit_TV-Dynamic: all
  FBSDKLoginKit-Universal:
    build:
      targets:
        FBSDKLoginKit-Universal: all
      parallelizeBuild: false
  FBSDKLoginKit_TV-Universal:
    build:
      targets:
        FBSDKLoginKit_TV-Universal: all
      parallelizeBuild: false
